### ISSUE TITLE
Point Ladders

### ISSUE THREAD

**Issue by GothicLoco** [Naiten/RoW-Issues#1]
This is related to a physics problem where a train is moving through a point ladder of a tight radius, with the wagons bumping into each-other whilst doing so.
I've also gone to have a look at the point ladder problem, and this is what I've found.

1.12.2-2202-1o1 ~ Yes
1.12.2-2006-1o1 ~ Yes
1.12.2-2004-2o1 ~ No
1.12.2-2004-1o8 ~ No
1.12.2-1901-9p1 ~ No

2006-1o1 came straight after 2004-2o1, so the former is kinda where the problem kicked off.

**Comment by Naiten** [comment]
The issue occured as the result of an attempt to improve the resolveCoupling() method and achieve less bouncy train physics. 
Appeared in the commit 2cc6fe9 / build 1.12.2-2006-1o1.
(2cc6fe96817c6404e19bd9579fc7210d0b01c0bc)
Reverted in build 1.12.2-241224-1.
